server:
  port: 8082
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://172.26.223.28:3306/stock?useUnicode=true&characterEncoding=utf8
        username: mysqladmin
        password: MPadmin
    application:
      name: stock-service

mybatis:
  type-aliases-package: com.rains.transaction.tx.dubbo.sample.stock.api.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        com.rains.bonuspoint: debug
        com.rains.lottery: debug
        com.rains: debug

    path: "./logs"

